name: Autobuild
# Shoutout to ChatGPT for helping me work through this cause I don't know anything
on:
  workflow_dispatch:
  push:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
#      - name: Install Visual Studio Build Tools
#        run: |
#          choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
#          choco install visualstudio2019-workload-vctools --package-parameters "--includeRecommended --includeOptional"

#      - name: Build Solution
#        run: |
#          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe /p:Configuration=Release /p:Platform=x86 NEPS.sln"
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app for release
        run: msbuild NEPS.sln -property:Configuration=Release -property:Platform=x86
        
 # EDIT NEVERMIND I KNOW WHAT I DID WRONG
      - name: Get it into the safe zone
        shell: cmd
        run: move /y Release\NEPS.dll NEPS.dll
        
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: NEPS
          path: NEPS.dll

 
  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current time
        id: current_time
        run: echo "::set-output name=time::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    
#      - name: Set release tag
#        uses: actions/github-script@v4
#        with:
#          script: |
#            const time = '${{ steps.current_time.outputs.time }}'
#            const tag = `v${time.replace(/[-T:Z]/g, '')}`
#            github.git.createRef({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              ref: `refs/tags/${tag}`,
#              sha: context.sha
#            })
#          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Release Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: NEPS

#      - name: Create release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.set_release_tag.outputs.result }}
#          release_name: Release ${{ steps.set_release_tag.outputs.result }}
#          body: |
#            Automatically compiled project with tag ${{ steps.set_release_tag.outputs.result }}.
#          draft: false
#          prerelease: false
          
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        id: "automatic_releases"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            NEPS.dll
